- name: Install software-properties-common
  apt:
    name: software-properties-common
    state: present

- name: Add apt-add-repository ppa:ansible/ansible
  apt_repository:
    repo: 'ppa:ansible/ansible'

- name: Install ansible
  apt:
    name: ansible
    state: present
    update_cache: yes
